### ISSUE TITLE
The first sample dose not work!

### ISSUE THREAD

**Issue by mironline-net** [wannesm/dtaidistance#72]
I am running the first sample code in a Windows environment with Python 3.8.3 : 

```
from dtaidistance import dtw
from dtaidistance import dtw_visualisation as dtwvis
import numpy as np
s1 = np.array([0., 0, 1, 2, 1, 0, 1, 0, 0, 2, 1, 0, 0])
s2 = np.array([0., 1, 2, 3, 1, 0, 0, 0, 2, 1, 0, 0, 0])
path = dtw.warping_path(s1, s2)
dtwvis.plot_warping(s1, s2, path, filename="warp.png")
```
but here is the result :

![warp](https://user-images.githubusercontent.com/54317731/82756745-07dac380-9daa-11ea-8747-d08ea23c4999.png)

is anything wrong with my device?

**Comment by nxtsuki** [comment]
Hello, i have the same issue, did you fix this?

**Comment by cbonesana** [comment]
@nxtsuki I fixed this issue by adding a `plt.tight_layout()` after line 94 in [dtw_visualisation.py](https://github.com/wannesm/dtaidistance/blob/master/dtaidistance/dtw_visualisation.py).

**Comment by michaelk-a-m** [comment]
Thanks @cbonesana, it works now!

**Comment by wannesm** [comment]
I cannot replicate the issue but I have added the tight_layout in any case. Thanks for the suggestion.

**Comment by keithbriggs** [comment]
I am getting this too.  There is something strange about the plt.tight_layout() suggestion.   That should not change the lines which are plotted, only the layout of ticks and axis labels.   This needs to be investigated and fixed properly.

**Comment by keithbriggs** [comment]
The plt.tight_layout() change does not fix it for me.   This is on a fully up-to-date Ubuntu 18 system with latest matplotlib, numpy etc.

**Comment by wannesm** [comment]
Turns out this was an issue with the order of drawing (which I assume can differ between versions/drivers/...). It is now fixed by using `ConnectionPatch` objects.
